db_conn = "postgresql://kabina:kaboot@192.168.10.176:5432/kabina"
run_after = 15
max_assign_time = 3
max_solver_size = 500
max_legs = 8
extend_margin = 1.4
max_angle = 120.0
cab_speed = 60
stop_wait = 1
log_file = "log/kern.log"
use_ext_pool = true
thread_numb = 10
pool4_size = 120
pool3_size = 300
pool2_size = 600