db_conn = "mysql://kabina:kaboot@127.0.0.1:3306/kabina"
run_after = 15
solver_delay = 35
max_assign_time = 3
max_legs = 10
max_angle = 120.0
max_angle_dist = 1
cab_speed = 30
stop_wait = 1
log_file = "log/kern.log"
use_pool = false
use_extern_pool = true # when 'false' change MAX_BRANCH_SIZE to 8000000
use_extender = false
thread_numb = 11
max_pool5_size = 40
max_pool4_size = 150
max_pool3_size = 650
max_pool2_size = 3000
max_solver_size = 3000