db_conn = "mysql://kabina:kaboot@localhost:3306/kabina"
run_after = 15
solver_interval = 4
max_assign_time = 3
max_legs = 10
max_angle = 120.0
max_angle_dist = 1
cab_speed = 30
stop_wait = 1
log_file = "log/kern.log"
use_pool = true
use_extern_pool = true
use_extender = true
thread_numb = 10
max_pool5_size = 50
max_pool4_size = 120
max_pool3_size = 440
max_pool2_size = 800
max_solver_size = 1400