db_conn = "postgresql://kabina:kaboot@localhost:5432/kabina"
run_after = 15
max_assign_time = 3
max_legs = 10
max_angle = 120.0
cab_speed = 60
stop_wait = 1
log_file = "log/kern.log"
use_ext_pool = true
use_extender = true
thread_numb = 10
max_pool4_size = 120
max_pool3_size = 300
max_pool2_size = 600
max_solver_size = 500