select 'Number of requests' AS' ';
select count(*) from taxi_order;
select 'total cabs used' AS' ';
select count(distinct(cab_id)) from taxi_order;
select 'avg wait (pick-up) time (secs)' AS' ';
select (select sum(TIMESTAMPDIFF(second, received, started)) from taxi_order where received is not null and started is not null)/(select count(*) from taxi_order where received is not null and started is not null);
select 'avg duration of all requests (secs)' AS' ';
select (select sum(TIMESTAMPDIFF(second, timestampadd(second, 60,started), completed)) from taxi_order where completed is not null and started is not null)/(select count(*) from taxi_order where completed is not null and started is not null);
select 'total distance driven' AS' ';
select sum(TIMESTAMPDIFF(second, started, completed))/120 from leg where completed is not null and started is not null;
select 'average number of passengers per route' AS' ';
select sum(order_count*route_count)/sum(route_count) FROM (SELECT order_count, COUNT(*) AS route_count from (SELECT route.id, count(taxi_order.id) as order_count from route left join taxi_order on (route.id = taxi_order.route_id) group by route.id) AS aa GROUP BY order_count) as counts;
select 'average passenger count in legs' AS' ';
select sum(passengers*pass_count)/sum(pass_count) from (select passengers,count(*) as pass_count from leg group by passengers) as average;
select 'average number of legs per route' AS' ';
select (select count(*) from leg) / (select count(*) from route);
select 'avg detour: total duration / total requested distance (we measure distance with time)' AS' ';
select ((select sum(TIMESTAMPDIFF(second, timestampadd(second, 60,started), completed)) from taxi_order where completed is not null and started is not null) / (select sum(distance*60) from taxi_order where completed is not null and started is not null)) as avg_detour;
select 'max scheduler time (seconds)' AS' ';
select * from stat where name='MaxSchedulerTime';
select 'average scheduler time (seconds)' AS' ';
select * from stat where name='AvgSchedulerTime';
select 'average pool finder input size (demand)' AS' ';
select * from stat where name='AvgPoolDemandSize';
select 'average solver input size (demand)' AS' ';
select * from stat where name='AvgSolverDemandSize';